// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcJwm9BMHpzLhUul4EFrQPdj3sbdRzd4U',
    appId: '1:625830992420:web:eb21fc3fc56a96435896b1',
    messagingSenderId: '625830992420',
    projectId: 'week2-7da87',
    authDomain: 'week2-7da87.firebaseapp.com',
    storageBucket: 'week2-7da87.firebasestorage.app',
    measurementId: 'G-G94J5YHZ4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVmYDQyu_yMbD_S07-8njAUxyJ20AJQic',
    appId: '1:625830992420:android:346b390d3f5621b95896b1',
    messagingSenderId: '625830992420',
    projectId: 'week2-7da87',
    storageBucket: 'week2-7da87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4zz015Q2WHga44ck6eCHXwDozUqEApU8',
    appId: '1:625830992420:ios:b23ec58c1d00231f5896b1',
    messagingSenderId: '625830992420',
    projectId: 'week2-7da87',
    storageBucket: 'week2-7da87.firebasestorage.app',
    iosBundleId: 'com.example.week2',
  );
}
